# http://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

def fibonacci_beneath(first, second, beneath)
  [first, fibonacci_beneath(second, first + second, beneath)].flatten.compact if first < beneath
end

puts "Answer: #{fibonacci_beneath(1, 2, 4000000).reduce(0) {|sum, n| n.even? ? sum + n : sum}}"
